### PR TITLE
Adapt transformers code to new agent streaming option

### PR DESCRIPTION
**Pull request by aymeric-roucher**
cc @freddyaboulton

### CODE REVIEW

**Review by freddyaboulton — COMMENTED** [review]
Code changes look good! 

One thing though is that I don't think we should use ">>>" for the final answer as that will get converted to markdown and look off (see below).

image

I think a single ">" should be enough. It will render as a "quote" and it will stand out:

> This was created with a single ">" at the start of the sentence

Another thing though is that sometimes the search tool yields a lot of observations and they don't render well in the UI. See below. Perhaps we can detect json and place it in a code block?

image

**Comment by freddyaboulton** [comment]
We can think about the second point a bit more. Just the first point needs to be addressed before merge imo.

**Comment by aymeric-roucher** [comment]
@freddyaboulton I've updated the code to have both Observations and Final answer in code blocks, with a **Final answer:** prefix for the final answer:
image
IMO it looks quite good, what do you think?

**Comment by freddyaboulton** [comment]
Awesome thanks for the PR @aymeric-roucher !

**Pull request merged**
